### ISSUE TITLE
Square versions

### ISSUE THREAD

**Issue by richardvenneman** [jackiboy/flagpack#1]
Do you plan to support the square versions of the FlagKit flags as well?

**Comment by jackiboy** [comment]
@richardvenneman I don't think that would be possible without creating seperate square svg icons for each flag.

**Comment by richardvenneman** [comment]
@jackiboy thanks for the quick reply. I assumed that FlagKit contained square resources, but now I see that they actually just clip the original resources:

https://github.com/madebybowtie/FlagKit/blob/4408c2dab3c792258dd083df71f511dd1d4c734b/Sources/Swift/FlagKit/Flag.swift#L50

**Comment by jackiboy** [comment]
@richardvenneman yeah :-/ it looks bad especially with flags that have for example the Union Jack in the top left corner. I might add square icons before v1.0.0 but it will be tedious to go through and edit all the files.

**Comment by richardvenneman** [comment]
@jackiboy awesome! Appreciated 🙏
