### ISSUE TITLE
flag classname with prefix

### ISSUE THREAD

**Issue by eltebe** [jackiboy/flagpack#2]
Hello,

**Problem:**
Same class name in two or more third party package, for example: 

> class="is" 

= Island flag

**Fix:**
Add a flag/country prefix (SASS variable) to class name: 

> $fp-country-prefix: 'flg' !default;

> class="flg-is"

I've completed that feature but I have no permission to commit or push into this repo.

**Comment by jackiboy** [comment]
@eltebe I have pushed version `1.0.4`. It now has a `$fp-prepend` sass variable which you can enable to get the functionality you are after.
