### ISSUE TITLE
Missing AC and TA flags

### ISSUE THREAD

**Issue by catamphetamine** [jackiboy/flagpack#3]
https://en.wikipedia.org/wiki/Flag_of_Ascension_Island
https://en.wikipedia.org/wiki/Flag_of_Tristan_da_Cunha

**Comment by riceboyler** [comment]
:+1:

**Comment by catamphetamine** [comment]
FYI: I have since slightly updated the flags.

https://raw.githubusercontent.com/catamphetamine/country-flag-icons/master/3x2/TA.svg

https://raw.githubusercontent.com/catamphetamine/country-flag-icons/master/3x2/AC.svg
